package wood;

import wood.util.UtilGPT;

// TODO use a JSON file to store settings
public class Settings {

    /** The default model to use for all API calls. */
    public static String model = UtilGPT.inDavinci;

    /** The maximum cost USD per API request from threads created by /prompt */
    public static double maxCostPerAPIRequest = .025;

    /** In the /prompt command, the number of tokens used in the API request's completion  */
    public static int promptCompletionTokens = 30;

    /** In the /chat command, the number of tokens used in the API request's completion  */
    public static int chatCompletionTokens = 30;

    /** Whether the names for threads created by /prompt should be generated by GPT-3 */
    public static boolean gptGeneratedThreadNames = true;

    /** If gptGeneratedThreadNames is false, then this will be the name for threads created by /prompt */
    public static String defaultThreadName = "GPT-3";

}